#!/bin/bash

# A script that uses to search zsh history using fzf 
# Usage : fzhist [item to search]

#Requirements: fzf

if [ $# != 1 ]; then
    echo "Please provide one argument with the script."
    exit 1
fi

#Adding exceptions : history items containing these terms will not be displayed
exceptions='hist|man|fzhist'

choice=$(cat ~/.zsh_history | grep "$1" | sort -u | uniq | grep -vwE "$exceptions" | fzf -i )






