#!/bin/bash
# kimport: import your kindle highlights and notes, organize them and copy the results to the clipboard
# Usage : kimport [Path to your My Clipping.txt kindle file]

# Requirements : 
# fzf
# xclip on x1 and wl-clipboard on wayland
# Testing that an argument was provided

if [ $# != 1 ]; then
    echo "Please provide path to My Clippings.txt file"
    exit 1
fi

#Use xclip on xorg
#Use wl-clipboard on Wayland

if [ "$XDG_SESSION_TYPE" = "x11" ]; then
    clipboard="xclip -sel clip"
elif [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    clipboard="wl-copy"
fi

# Convert My Clippings into a Bash array
readarray -t lines < "$1"

# Choose a book from a list of all available books
book="$(cat "$1" | sed -n '/====/{ n; p}' | sort -u | uniq | fzf)"

# loop over the array and get the highlights and notes

notes=""
for ((index=0; index < ${#lines[@]}; index++)); do
  if [[ "${lines[index]}" == *"$book"* ]] && [[ "${lines[index+1]}" == *"Highlight"* ]]; then
    notes="${notes}\n* ${lines[index+3]}"
  elif [[ "${lines[index]}" == *"$book"* ]] && [[ "${lines[index+1]}" == *"Note"* ]]; then
    notes="${notes}\n*** ${lines[index+3]}"
  fi
done

# copy the content into the clipboard
printf "$notes" | $clipboard


